default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-todo_development
  username: dev
  password: dev
  host: localhost
  port: 5432

test:
  <<: *default
  database: rails-todo_test

production:
  <<: *default
  database: rails-todo_production
  username: rails-todo
  password: <%= ENV['RAILS-TODO_DATABASE_PASSWORD'] %>
